### ISSUE TITLE
Integration with file picker provided by Cat-a-lot

### ISSUE THREAD

**Issue by valerio-bozzolan** [lucaswerkmeister/ACDC#12]
At the moment the ACDC tool allows to manually type the name of some files but it does not allow to pick only _some_ files so easily like [Cat-a-lot](https://commons.wikimedia.org/wiki/Help:Cat-a-lot) allows instead by just clicking on them.

## Proposed feature

Integrate ACDC with the Cat-a-lot file picker:
![Cat-a-lot ACDC Wikimedia file picker](https://user-images.githubusercontent.com/6052909/144866711-6b8dffbb-50d3-40bc-be7d-0a5f6cce59d0.png)

## Steps to reproduce
1. use a desktop computer
2. login in Wikimedia Commons
3. go in [[Special:Preferences#mw-prefsection-gadgets]]
4. enable ''Add to Commons / Descriptive Claims (ACDC)''
5. enable ''Cat-a-lot''
6. go to a random page like [[:Category:Red Hat]]
7. click on CatALot in the bottom-down corner (it's a small yellow box)
8. click on a couple of random images (they will become yellow)
9. click on the blue link ''AC/DC'' on the left sidebar
10. At this point the field ''Files to edit'' is empty.

The last step n.10, instead of being empty, should list all the selected files in yellow (selected from step n. 8).

## Success check

Given the above steps to reproduce, the field is not empty but you can operate instead on the selected files.

## Tips

Note that the Cat-a-lot elements can be retrieved with this method:

```
mw.libs.catALot.getMarkedLabels()
```

Returning an array of arrays. For each element, the file title it's in the zero position.

E.g.

```
[ [ "File:asd.gif", .. ] ]
```

**Comment by valerio-bozzolan** [comment]
I'm asking around for an economical quote.

Sorry @lucaswerkmeister but can I count on you for a small code review when the code will be ready? :rocket: 

Thank you :)

**Comment by lucaswerkmeister** [comment]
This use case is exactly what I created the [PagePile Visual Filter](https://pagepile-visual-filter.toolforge.org/) tool for ([documentation](https://commons.wikimedia.org/wiki/User:Lucas_Werkmeister/PagePile_Visual_Filter), [demonstration with AC/DC](https://commons.wikimedia.org/wiki/File:Wikimania_Hackathon_2019_showcase_%E2%80%93_PagePile_Visual_Filter.pdf)). You create a PagePile using a tool of your choice (e.g. PetScan), filter it visually in a manner similar to Cat-a-lot, then reuse it in another tool (e.g. AC/DC). This seems more scalable to me than adding support specifically for Cat-a-lot to a lot of tools.

I would prefer you don’t find a paid developer for this, because I don’t think it’s likely the code review will be small, and I think there’s a good chance I’d have to mostly rewrite their contribution so I’m happy with the code style and everything.

**Comment by lucaswerkmeister** [comment]
See also #13 :)

**Comment by valerio-bozzolan** [comment]
>  would prefer you don’t find a paid developer for this

Oh, OK.

> This use case is exactly what I created the PagePile Visual Filter tool

Tell me if I'm wrong but I see that Cat-a-lot is perfectly integrated within MediaWiki, while that mentioned tool it's not if I understand correctly.

Anyway I've found that it's damn easy to have support to Cat-a-lot since we can access this method:

```
mw.libs.catALot.getMarkedLabels()
```

That returns kind of an array of arrays with all the selected elements.

**Comment by lucaswerkmeister** [comment]
I don’t understand what ”perfectly integrated within MediaWiki” is supposed to mean in this context…

And while this `getMarkedLabels()` method sounds very useful – is it documented anywhere? Is it stable? If we start using it in AC/DC, who guarantees us that it will continue working? (It doesn’t look like any other gadget uses it, as far as I can tell.)

**Comment by lucaswerkmeister** [comment]
> That's often a category page, but Cat-a-lot can also be used on other pages, like your uploads page or on the search page.

Ah, I didn’t know that. (In my defense, it’s not exactly obvious from the name – but then again, I created Wikidata Image Positions, a tool that started out to view image positions on Wikidata but by now is neither limited to Wikidata nor viewing…)

Alright, I’ll add this and just hope that it doesn’t break.
