### ISSUE TITLE
Make AC/DC batches undo-able with EditGroups on Commons?

### ISSUE THREAD

**Issue by trnstlntk** [lucaswerkmeister/ACDC#15]
Would it be possible to make AC/DC batches undo-able with [EditGroups on Wikimedia Commons](https://commons.wikimedia.org/wiki/Commons:Edit_groups/Adding_a_tool)? I see that you [apparently already made it work for QuickCategories](https://commons.wikimedia.org/wiki/Commons_talk:Edit_groups/Adding_a_tool) :-)

**Comment by lucaswerkmeister** [comment]
Thanks! I think someone suggested this back before EditGroups for Commons existed, and then I didn’t realize that it could be added to AC/DC when Commons EditGroups eventually came around.

I’m not sure how exactly to handle it, though. I think I have two questions:
- Should we always generate an edit group, or only sometimes? If only sometimes: depending on what? I could imagine an automatic condition (e.g. affects ≥10 files), or a user choice (see next question).
- Should we only generate untitled edit groups (with a small “details” link at the end of the summary), or do we want to give users the option to write an edit summary as well? (I think an edit summary wouldn’t have been possible in the initial version of AC/DC, but I now realize that technically it should be easily doable since 5eb42a4be89.) In that case, how do we get the edit summary from the user? (I’m worried that a prompt when clicking the Publish button might be too disruptive.)

**Comment by trnstlntk** [comment]
Thanks for following up on this, Lucas :-)

My two cents:

1. Generating an edit group for edits affecting ≥ 10 files sounds great. Manually undo-ing edits to more than 10 files begins to get annoying.
2. I personally would not prompt the user to create edit summaries. IMO one of AC/DC's strengths is its speed and simplicity. Providing the user with an additional prompt would indeed be a bit disruptive, I think.

**Comment by lucaswerkmeister** [comment]
Alright, then let’s go with that for now and see if anyone asks for more control after announcing it :)

**Comment by lucaswerkmeister** [comment]
Alright, it’s deployed to Commons now. Can you see if it works? (It can’t be tested on Test or Beta Commons, and I don’t think I have a real set of ≥10 AC/DC edits to make at the moment.)
